# Generated by Django 4.1.3 on 2022-11-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvuploads',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
