# Generated by Django 4.1.3 on 2022-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cvuploads_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvuploads',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
